stages:
  - test
  - build
  - push
  - deploy

variables:
  IMAGE: registry.gitlab.com/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:$CI_COMMIT_SHORT_SHA

test:
  stage: test
  script:
    - pip install -r requirements.txt
    - pytest -v

build:
  stage: build
  script:
    - docker build -t $IMAGE .
  tags:
    - docker

push:
  stage: push
  script:
    - docker push $IMAGE
  tags:
    - docker

deploy:
  stage: deploy
  script:
    - helm upgrade --install hello ./helm --set image.repository=registry.gitlab.com/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME --set image.tag=$CI_COMMIT_SHORT_SHA
  tags:
    - k8s
  only:
    - main
